import { IconType } from "react-icons";
import {
  FaReact,
  FaAws,
  FaDocker,
  FaPython,
  FaGitAlt,
  FaNodeJs,
  FaGithub,
  FaDatabase,
} from "react-icons/fa";
import {
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiMongodb,
  SiFirebase,
  SiExpress,
  SiJira,
  SiPostgresql,
  SiPrisma,
  SiSupabase,
  SiVercel,
  SiVite,
  SiRedis,
  SiGooglecloud,
  SiOpenai,
  SiAnthropic,
  SiFigma,
  SiFramer,
  SiShadcnui,
  SiStorybook,
  SiGo,
  SiNestjs,
  SiGraphql,
  SiMysql,
  SiElasticsearch,
  SiPostman,
} from "react-icons/si";

export const TechIconMap = {
  FaReact,
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiVite,
  SiFramer,
  SiShadcnui,
  SiStorybook,
  FaNodeJs,
  SiExpress,
  SiNestjs,
  FaPython,
  SiGo,
  SiPrisma,
  SiGraphql,
  FaDatabase,
  SiMongodb,
  SiFirebase,
  SiPostgresql,
  SiMysql,
  SiSupabase,
  SiRedis,
  SiElasticsearch,
  FaAws,
  SiGooglecloud,
  SiOpenai,
  SiAnthropic,
  FaDocker,
  FaGitAlt,
  SiJira,
  SiVercel,
  FaGithub,
  SiFigma,
  SiPostman,
} as const satisfies Record<string, IconType>;

export type TechIconKey = keyof typeof TechIconMap;
export type FormTechIconKey = TechIconKey | "";
