import { IconType } from "react-icons";
import {
  FaAws,
  FaDocker,
  FaPython,
  FaGitAlt,
  FaNodeJs,
  FaHtml5,
  FaCss3Alt,
} from "react-icons/fa";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiShadcnui,
  SiNestjs,
  SiGo,
  SiGraphql,
  SiPostgresql,
  SiMongodb,
  SiSupabase,
  SiFirebase,
  SiPrisma,
  SiRedis,
  SiOpenai,
  SiAnthropic,
  SiGooglegemini,
  SiGooglecloud,
  SiVercel,
  SiVite,
  SiJest,
  SiZod,
  SiFigma,
  SiPostman,
  SiJavascript,
  SiExpress,
  SiJsonwebtokens,
  SiReactrouter,
  SiReactquery,
  SiAxios,
  SiFramer,
  SiLucide,
  SiExpo,
  SiAmazonec2,
  SiHono,
  SiCloudflareworkers,
  SiDrizzle,
  SiVitest,
  SiGithubactions,
} from "react-icons/si";
import { VscAzure } from "react-icons/vsc";
import {
  ZustandIcon,
  PlaywrightIcon,
  DexieIcon,
  PdfJsIcon,
} from "@/services/utils/custom-tech-icons";

/** Tech stack icons. Updated for enhanced project visualization. */
export const TechIconMap = {
  // Frontend & Fundamentals
  FaHtml5,
  FaCss3Alt,
  SiJavascript,
  SiReact,
  SiExpo,
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiShadcnui,
  SiReactrouter,
  SiReactquery,
  SiFramer,
  SiLucide,
  // State Management
  ZustandIcon,
  // Backend & Security
  SiNestjs,
  FaNodeJs,
  SiExpress,
  SiHono,
  SiGo,
  FaPython,
  SiGraphql,
  SiJsonwebtokens,
  SiAxios,
  // Database
  SiPostgresql,
  SiMongodb,
  SiSupabase,
  SiFirebase,
  SiPrisma,
  SiRedis,
  SiDrizzle,
  DexieIcon,
  // AI
  SiOpenai,
  SiAnthropic,
  SiGooglegemini,
  // Infra
  FaAws,
  SiAmazonec2,
  SiGooglecloud,
  VscAzure,
  FaDocker,
  SiVercel,
  SiCloudflareworkers,
  // Tools & Testing
  SiVite,
  SiJest,
  SiVitest,
  PlaywrightIcon,
  SiZod,
  FaGitAlt,
  SiGithubactions,
  SiFigma,
  SiPostman,
  PdfJsIcon,
} as const satisfies Record<string, IconType>;

export type TechIconKey = keyof typeof TechIconMap;
export type FormTechIconKey = TechIconKey | "";